validation:
  content: 500
  name: 255
  description: 500
  quantity: 0
  address: 255
  full_name: 255
  phone: 15
  point: 0
  price: 0
  email: 255
  password: 6
  user_name_max: 15
  user_name_min: 3
image:
  profile_upload_size: "300x300"
login:
  remember_me: "1"
recently_viewed:
  per_page: 5
  size: 12
max_rate: 5
min_rate: 1
paginate:
  product_show: 12
  user_per_page: 10
  recently_viewed: 10
  hot_trend_products: 12
  top_new_products: 12
average_rate_round: 2
search_form:
  max_price: 10000000
  min_price: 0
  slider_step: 100000
  slider_value: "[0, 2000000]"
average_rate_round: 2
cookie_recently_viewed: 20
order_status:
  default: 1
product_add_to_cart_default: 1
chart_type:
  number_of_product_day: 1
  number_of_product_month: 2
  number_of_product_year: 3
  income_of_product_day: 4
  income_of_product_month: 5
  income_of_product_year: 6
  income_daily: 7
  income_monthy: 8
  income_yearly: 9
